services:
  postgres:
    image: postgres:16
    hostname: db
    environment:
      POSTGRES_DB: ktaxes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
